// <auto-generated />
using System;
using Klient.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Klient.Model.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190803222517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Klient.Model.Entities.AdresEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Miasto");

                    b.Property<string>("NrDomu");

                    b.Property<string>("NrMieszkania");

                    b.Property<string>("Ulica");

                    b.HasKey("Id");

                    b.ToTable("Adres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b578c8c-8dd4-4fb7-a114-eecca9f4d5c4"),
                            Miasto = "Toruń",
                            NrDomu = "22",
                            NrMieszkania = "1",
                            Ulica = "Biała"
                        });
                });

            modelBuilder.Entity("Klient.Model.Entities.KlientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdresId");

                    b.Property<string>("Imie");

                    b.Property<string>("Nazwisko");

                    b.Property<string>("Pesel");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Klient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f882bf5-446e-4407-90f5-cdc3dabe15f7"),
                            AdresId = new Guid("9b578c8c-8dd4-4fb7-a114-eecca9f4d5c4"),
                            Imie = "Szymek",
                            Nazwisko = "Kolt",
                            Pesel = "95232125123"
                        });
                });

            modelBuilder.Entity("Klient.Model.Entities.KlientEntity", b =>
                {
                    b.HasOne("Klient.Model.Entities.AdresEntity", "Adres")
                        .WithMany("Klient")
                        .HasForeignKey("AdresId");
                });
#pragma warning restore 612, 618
        }
    }
}
