// <auto-generated />
using System;
using Klient.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Klient.Model.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Klient.Model.Entities.AdresEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Miasto")
                        .HasMaxLength(60);

                    b.Property<string>("NrDomu");

                    b.Property<string>("NrMieszkania");

                    b.Property<string>("Ulica");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Klient.Model.Entities.KlientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdresId");

                    b.Property<string>("Imie");

                    b.Property<string>("Nazwisko");

                    b.Property<string>("Pesel");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Klient");
                });

            modelBuilder.Entity("Klient.Model.Entities.KlientEntity", b =>
                {
                    b.HasOne("Klient.Model.Entities.AdresEntity", "Adres")
                        .WithMany("Klient")
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
